
bi_model_acc <- accordion( 
  style = "background-color: white;",
  p(tags$strong("Please ensure you have set the desired model specifications on this sidebar and defined the applicable population sizes (see right).")),
  p("Optional: Add any additional one-time costs here (e.g., inital IT infrastucture setup)"),
  div(
    style = "display: flex; align-items: center;",
    tags$label("Regional level"),
    numericInput("SI_BI_one_time_option_reg", label = NULL, value = 0, min = 0, max = 10000000, step = 1)
  ),
  div(
    style = "display: flex; align-items: center;",
    tags$label("National level"),
    numericInput("SI_BI_one_time_option_nat", label = NULL, value = 0, min = 0, max = 10000000, step = 1)
  ),
  accordion_panel(
    style = "background-color: white;",
    "Subgroup & effects",
    sliderInput(inputId = "SI_BI_n_age_init",
                label = "Initial Age",
                value = 50,
                min = 50,
                max = 80),
    radioButtons(inputId="SI_BI_subgroup", 
                 label="Patient Subgroup",
                 choices=c("Pooled" = "pooled",
                           "Controlled BP, no history of Stroke/MI" = "CN",
                           "Uncontrolled BP, no history of Stroke/MI" = "UN",
                           "Controlled BP, history of Stroke/MI" = "CY",
                           "Uncontrolled BP, history of Stroke/MI" = "UY"),
                 inline = FALSE),
    numericInput(inputId = "SI_BI_sbp_diff_controlled",   
                 label = "Reduction in mmHg (controlled subgroup)",
                 value = 1.3,              
                 min = 0,
                 max = 20,
                 step = 0.1),
    numericInput(inputId = "SI_BI_sbp_diff_controlled_SE",   
                 label = "Standard error of above",
                 value = 1.4,              
                 min = 0,
                 max = 20,
                 step = 0.1),
    numericInput(inputId = "SI_BI_sbp_diff_uncontrolled",   
                 label = "Reduction in mmHg (uncontrolled subgroup)",
                 value = 3.5,              
                 min = 0,
                 max = 20,
                 step = 0.1),
    numericInput(inputId = "SI_BI_sbp_diff_uncontrolled_SE",   
                 label = "Standard error of above",
                 value = 2.1,              
                 min = 0,
                 max = 20,
                 step = 0.1)
  ),
  accordion_panel(
    style = "background-color: white;",
    "Intervention Costs",
    numericInput(inputId = "SI_BI_c_device_strA",
                 label = "Device cost", 
                 value = round(150*1.038,1),              
                 min = 10,                   
                 max = 4000,
                 step = 1),
    numericInput(inputId = "SI_BI_c_device_shipping", 
                 label = "Device packaging & shipping",       
                 value = round(30*1.038,1),              
                 min = 0,                   
                 max = 100,
                 step = 1),
    numericInput(inputId = "SI_BI_c_personnel_strA",     
                 label = "Personnel (1-time)",       
                 value = round(25*1.038,1),              
                 min = 0,                   
                 max = 4000,
                 step = 1), 
    numericInput(inputId = "SI_BI_c_strA_controlled_mean",     
                 label = "Mean (annual) controlled BP",       
                 value = round(84.83*1.038,1),              
                 min = 0,                   
                 max = 4000,
                 step = 1),
    numericInput(inputId = "SI_BI_c_strA_uncontrolled_mean",     
                 label = "Mean (annual) uncontrolled BP",       
                 value = round(90.27*1.038,1),              
                 min = 0,                   
                 max = 4000,
                 step = 1)
  ),
  accordion_panel(
    style = "background-color: white;",
    "SOC Costs",
    numericInput(inputId = "SI_BI_c_SOC_controlled_mean",     
                 label = "Mean (annual) controlled BP",       
                 value = round(58.65*1.038,1),              
                 min = 0,                   
                 max = 4000,
                 step = 1),
    numericInput(inputId = "SI_BI_c_SOC_uncontrolled_mean",     
                 label = "Mean (annual) uncontrolled BP",       
                 value = round(73.34*1.038,1),              
                 min = 0,                   
                 max = 4000,
                 step = 1)
  )
)


