
eg_model_acc <- accordion( 
  style = "background-color: white;",
  p(tags$strong("Please ensure you have set the desired specifications on this sidebar and defined the applicable population sizes (see right).")),
  p(tags$strong("Proportion with uncontrolled BP")),
  div(style = "display: flex; align-items: center;",
      tags$label("Uncontrolled BP", style = "margin-right: 20px; white-space: nowrap;"),
      numericInput(inputId = "SI_EG_uncontrolled_prop",   
                   label = NULL,
                   value = 0.394,              
                   min = 0,
                   max = 1,
                   step = 0.01,
                   width = '100px')),
  p(tags$strong("Visit durations (in minutes)")),
  div(style = "display: flex; align-items: center;",
      tags$label("GP, short visit", style = "margin-right: 20px; white-space: nowrap;"),
      numericInput(inputId = "SI_EG_duration_GP_short",   
                   label = NULL,
                   value = 10,              
                   min = 0,
                   max = 20,
                   step = 0.1,
                   width = '100px')),
  div(style = "display: flex; align-items: center;",
      tags$label("GP, long visit", style = "margin-right: 20px; white-space: nowrap;"),
      numericInput(inputId = "SI_EG_duration_GP_long",   
               label = NULL,
               value = 20,              
               min = 0,
               max = 40,
               step = 0.1,
               width = '100px')),
  div(style = "display: flex; align-items: center;",
      tags$label("POH, short visit", style = "margin-right: 20px; white-space: nowrap;"),
      numericInput(inputId = "SI_EG_duration_POH_short",   
               label = NULL,
               value = 15,              
               min = 0,
               max = 50,
               step = 0.1,
               width = '100px')),
  div(style = "display: flex; align-items: center;",
      tags$label("POH, long visit", style = "margin-right: 20px; white-space: nowrap;"),
      numericInput(inputId = "SI_EG_duration_POH_long",   
               label = NULL,
               value = 30,              
               min = 0,
               max = 60,
               step = 0.1,
               width = '100px')),
  div(style = "display: flex; align-items: center;",
      tags$label("Eligible CVD population per ref. practice", style = "margin-right: 20px; white-space: nowrap;"),
      numericInput(inputId = "SI_EG_cvd_pop_catchment",   
                   label = NULL,
                   value = round(420*0.55,0),              
                   min = 0,
                   max = 4000,
                   step = 1,
                   width = '100px')),
  div(style = "display: flex; align-items: center;",
      tags$label("Number of GPs in ref. practice", style = "margin-right: 20px; white-space: nowrap;"),
      numericInput(inputId = "SI_EG_n_gp_ref",   
                   label = NULL,
                   value = 1,              
                   min = 0,
                   max = 4,
                   step = 0.1,
                   width = '100px')),
  div(style = "display: flex; align-items: center;",
      tags$label("Number of PNs in ref. practice", style = "margin-right: 20px; white-space: nowrap;"),
      numericInput(inputId = "SI_EG_n_POH_ref",   
                   label = NULL,
                   value = 0.83,              
                   min = 0,
                   max = 4,
                   step = 0.01,
                   width = '100px'))
)


