
he_model_acc <- accordion( 
  accordion_panel(
    style = "background-color: white;",
    "General specifications",
    sliderInput(inputId = "SI_n_age_init",
                label = "Initial Age",
                value = 50,
                min = 40,
                max = 80),
    radioButtons(inputId = "SI_perspective",
                 label = "Perspective",
                 choices = c("Healthcare" = "healthcare",
                             "Societal" = "societal"),
                 inline = TRUE),
    radioButtons(inputId = "SI_subgroup",
                 label = "Patient Subgroup",
                 choices = c("Controlled BP, no history of Stroke/MI" = "CN",
                             "Uncontrolled BP, no history of Stroke/MI" = "UN",
                             "Controlled BP, history of Stroke/MI" = "CY",
                             "Uncontrolled BP, history of Stroke/MI" = "UY",
                             "Pooled" = "pooled"),
                 inline = FALSE),
    numericInput(inputId = "SI_prop_male",
                 label = "Proportion of males",
                 value = 0.531,
                 min = 0,
                 max = 1,
                 step = 0.1),
    numericInput(inputId = "SI_d_e",
                 label = "Disc. rate effect (%)",
                 value = 1.5,
                 min = 0.0,
                 max = 5,
                 step = 0.1),
    numericInput(inputId = "SI_d_c",
                 label = "Disc. rate costs (%)",
                 value = 3,
                 min = 0.0,
                 max = 5,
                 step = 0.1)
  ),
  accordion_panel(
    style = "background-color: white;",
    "SBP Reduction",
    numericInput(inputId = "SI_sbp_diff_controlled",
                 label = "Reduction in mmHg (controlled subgroup)",
                 value = 1.3,
                 min = 0,
                 max = 20,
                 step = 0.1),
    numericInput(inputId = "SI_sbp_diff_controlled_SE",
                 label = "Standard error of above",
                 value = 1.4,
                 min = 0,
                 max = 20,
                 step = 0.1),
    numericInput(inputId = "SI_sbp_diff_uncontrolled",
                 label = "Reduction in mmHg (uncontrolled subgroup)",
                 value = 3.5,
                 min = 0,
                 max = 20,
                 step = 0.1),
    numericInput(inputId = "SI_sbp_diff_uncontrolled_SE",
                 label = "Standard error of above",
                 value = 2.1,
                 min = 0,
                 max = 20,
                 step = 0.1),
    numericInput(inputId = "SI_year_reduction_effect",
                 label = "Year reduction effect",
                 value = 1,
                 min = 1,
                 max = 20,
                 step = 0.1),
    numericInput(inputId = "SI_percentage_reduction_effect",
                 label = "Percentage reduction effect",
                 value = 0,
                 min = 0,
                 max = 100,
                 step = 0.1)
  ),
  accordion_panel(
    style = "background-color: white;",
    "Intervention Costs",
    numericInput(inputId = "SI_c_device_strA",
                 label = "Device cost (1-time)",
                 value = round(150*1.038,1),
                 min = 10,
                 max = 4000,
                 step = 1),
    numericInput(inputId = "SI_c_device_shipping",
                 label = "Device packaging & shipping (1-time)",
                 value = round(30*1.038,1),
                 min = 0,
                 max = 100,
                 step = 1),
    numericInput(inputId = "SI_c_personnel_strA",
                 label = "Personnel (1-time)",
                 value = round(25*1.038,1),
                 min = 0,
                 max = 4000,
                 step = 1),
    numericInput(inputId = "SI_c_strA_controlled_mean",
                 label = "Mean (annual) controlled BP",
                 value = round(84.83*1.038,1),
                 min = 0,
                 max = 4000,
                 step = 1),
    numericInput(inputId = "SI_c_strA_uncontrolled_mean",
                 label = "Mean (annual) uncontrolled BP",
                 value = round(90.27*1.038,1),
                 min = 0,
                 max = 4000,
                 step = 1)
  ),
  accordion_panel(
    style = "background-color: white;",
    "SOC Costs",
    numericInput(inputId = "SI_c_SOC_controlled_mean",
                 label = "Mean (annual) controlled BP",
                 value = round(58.65*1.038,1),
                 min = 0,
                 max = 4000,
                 step = 1),
    numericInput(inputId = "SI_c_SOC_uncontrolled_mean",
                 label = "Mean (annual) uncontrolled BP",
                 value = round(73.34*1.038,1),
                 min = 0,
                 max = 4000,
                 step = 1)
  )
)


